/**
** https://www.geeksforgeeks.org/print-subsequences-string/
** https://www.youtube.com/watch?v=KCEPvdLqlYI
** Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 

** Input : abc
** Output : a, b, c, ab, bc, ac, abc

** Input : aaa
** Output : a, aa, aaa
** Approach : At every step, we have two choice either to include first letter or exclude.
** Time Complexity: O(2^n)
** Space Complexity: O(2^n) //recursive stack
**/

Class Solution{

  public void printSubSequence(String input, String output){
    
    //Base Case
    if(input.length() == 0){
      if(output.length()!=0){ // Print only non empty subbstring
        System.out.println(output);
      }
      return ;
    }
    
    printSubSequence(input.substring(1), output); // exclude first character
    printSubSequence(input.substring(1), output+input.charAt(0)); // include first character
  }

}
